name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to cPanel
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e

            export PATH="/opt/cpanel/ea-nodejs20/bin:$PATH"

            cd /home/metacodecx/gggg.metacodecx.com

            echo "Node version:"
            node -v

            echo "NPM version:"
            npm -v

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing dependencies..."
            npm ci

            echo "Restarting PM2..."
            pm2 restart ci-cd-demo

            echo "Deployment completed!"